import { Inter } from 'next/font/google';
import 'swiper/css';
import './globals.css';
import Header from '@/components/layouts/header/Header';
import Footer from '@/components/layouts/footer/Footer';
import { ScrollToTop } from '@/components/ScrollToTopBtn';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'USA Website Design',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />

        <ScrollToTop />
      </body>
    </html>
  );
}
